name: fin-health
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - -r requirements.txt
      # Dev / analysis tools
      - numpy
      - matplotlib
      - seaborn
      - plotly
      - jupyterlab
      - ipykernel
      - quarto-cli
      - quartodoc
      # Linting
      - ruff
      # Testing
      - pytest
      - pytest-cov
      - pytest-raises
      - pytest-randomly
      - pytest-xdist
      - pytest-playwright